//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppletDashIndex {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DashIndex {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DashIndex() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppletSoftware.App_GlobalResources.DashIndex", typeof(DashIndex).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string appletdashactive {
            get {
                return ResourceManager.GetString("appletdashactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Manager.
        /// </summary>
        public static string appletdashaddmanagerbutton {
            get {
                return ResourceManager.GetString("appletdashaddmanagerbutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Manager.
        /// </summary>
        public static string appletdashaddmanagertitle {
            get {
                return ResourceManager.GetString("appletdashaddmanagertitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string appletdashclientaddress {
            get {
                return ResourceManager.GetString("appletdashclientaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string appletdashclientcompany {
            get {
                return ResourceManager.GetString("appletdashclientcompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Address in Arabic.
        /// </summary>
        public static string appletdashclientcompanyaddressarabic {
            get {
                return ResourceManager.GetString("appletdashclientcompanyaddressarabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Address in English.
        /// </summary>
        public static string appletdashclientcompanyaddressenglish {
            get {
                return ResourceManager.GetString("appletdashclientcompanyaddressenglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name in Arabic.
        /// </summary>
        public static string appletdashclientcompanynamearabic {
            get {
                return ResourceManager.GetString("appletdashclientcompanynamearabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name in English.
        /// </summary>
        public static string appletdashclientcompanynameenglish {
            get {
                return ResourceManager.GetString("appletdashclientcompanynameenglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbox.
        /// </summary>
        public static string appletdashclientordersinbox {
            get {
                return ResourceManager.GetString("appletdashclientordersinbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Name.
        /// </summary>
        public static string appletdashclientordersplanname {
            get {
                return ResourceManager.GetString("appletdashclientordersplanname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Email.
        /// </summary>
        public static string appletdashclientorderssearchbyemail {
            get {
                return ResourceManager.GetString("appletdashclientorderssearchbyemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneNumber.
        /// </summary>
        public static string appletdashclientphonenumber {
            get {
                return ResourceManager.GetString("appletdashclientphonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Company Name.
        /// </summary>
        public static string appletdashclientsearchbycompany {
            get {
                return ResourceManager.GetString("appletdashclientsearchbycompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by PhoneNumber.
        /// </summary>
        public static string appletdashclientsearchbyphonenumber {
            get {
                return ResourceManager.GetString("appletdashclientsearchbyphonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients Report.
        /// </summary>
        public static string appletdashclientsreport {
            get {
                return ResourceManager.GetString("appletdashclientsreport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Categories.
        /// </summary>
        public static string appletdasheditcategorybreadcrums {
            get {
                return ResourceManager.GetString("appletdasheditcategorybreadcrums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Details.
        /// </summary>
        public static string appletdasheditcategorydetails {
            get {
                return ResourceManager.GetString("appletdasheditcategorydetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Details.
        /// </summary>
        public static string appletdasheditclientdetails {
            get {
                return ResourceManager.GetString("appletdasheditclientdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Photo.
        /// </summary>
        public static string appletdasheditclientphoto {
            get {
                return ResourceManager.GetString("appletdasheditclientphoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Client.
        /// </summary>
        public static string appletdasheditclientsbreadcrumbs {
            get {
                return ResourceManager.GetString("appletdasheditclientsbreadcrumbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Managers.
        /// </summary>
        public static string appletdasheditmanagerbreadcrumbs {
            get {
                return ResourceManager.GetString("appletdasheditmanagerbreadcrumbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager Details.
        /// </summary>
        public static string appletdasheditmanagerdetails {
            get {
                return ResourceManager.GetString("appletdasheditmanagerdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager Password.
        /// </summary>
        public static string appletdasheditmanagerpassword {
            get {
                return ResourceManager.GetString("appletdasheditmanagerpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager Photo.
        /// </summary>
        public static string appletdasheditmanagerphoto {
            get {
                return ResourceManager.GetString("appletdasheditmanagerphoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit News.
        /// </summary>
        public static string appletdasheditnewsbreadcrums {
            get {
                return ResourceManager.GetString("appletdasheditnewsbreadcrums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Details.
        /// </summary>
        public static string appletdasheditnewsdetails {
            get {
                return ResourceManager.GetString("appletdasheditnewsdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Photo.
        /// </summary>
        public static string appletdasheditnewsphoto {
            get {
                return ResourceManager.GetString("appletdasheditnewsphoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Plan.
        /// </summary>
        public static string appletdasheditplansbreadcrumbs {
            get {
                return ResourceManager.GetString("appletdasheditplansbreadcrumbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Details.
        /// </summary>
        public static string appletdasheditplansdetails {
            get {
                return ResourceManager.GetString("appletdasheditplansdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Projects.
        /// </summary>
        public static string appletdasheditprojectbreadcrumbe {
            get {
                return ResourceManager.GetString("appletdasheditprojectbreadcrumbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Details.
        /// </summary>
        public static string appletdasheditprojectdetails {
            get {
                return ResourceManager.GetString("appletdasheditprojectdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Photo.
        /// </summary>
        public static string appletdasheditprojectphoto {
            get {
                return ResourceManager.GetString("appletdasheditprojectphoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Employee.
        /// </summary>
        public static string appletdasheditteamsbreadcrumsb {
            get {
                return ResourceManager.GetString("appletdasheditteamsbreadcrumsb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Details.
        /// </summary>
        public static string appletdasheditteamsdetails {
            get {
                return ResourceManager.GetString("appletdasheditteamsdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Photo.
        /// </summary>
        public static string appletdasheditteamseditphoto {
            get {
                return ResourceManager.GetString("appletdasheditteamseditphoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer in Arabic.
        /// </summary>
        public static string appletdashedittestmonialsanswerarabic {
            get {
                return ResourceManager.GetString("appletdashedittestmonialsanswerarabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer in English.
        /// </summary>
        public static string appletdashedittestmonialsanswerenglish {
            get {
                return ResourceManager.GetString("appletdashedittestmonialsanswerenglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Testmonials.
        /// </summary>
        public static string appletdashedittestmonialsbreadcrumbs {
            get {
                return ResourceManager.GetString("appletdashedittestmonialsbreadcrumbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category in English.
        /// </summary>
        public static string appletdashedittestmonialscategoryenglish {
            get {
                return ResourceManager.GetString("appletdashedittestmonialscategoryenglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Name in Arabic.
        /// </summary>
        public static string appletdashedittestmonialsclientnamearabic {
            get {
                return ResourceManager.GetString("appletdashedittestmonialsclientnamearabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Name in English.
        /// </summary>
        public static string appletdashedittestmonialsclientnameenglish {
            get {
                return ResourceManager.GetString("appletdashedittestmonialsclientnameenglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Photo.
        /// </summary>
        public static string appletdashedittestmonialsclientphoto {
            get {
                return ResourceManager.GetString("appletdashedittestmonialsclientphoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testmonial DateTime.
        /// </summary>
        public static string appletdashedittestmonialsdatetime {
            get {
                return ResourceManager.GetString("appletdashedittestmonialsdatetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testmonial Details.
        /// </summary>
        public static string appletdashedittestmonialsdetails {
            get {
                return ResourceManager.GetString("appletdashedittestmonialsdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client JobTitle in Arabic.
        /// </summary>
        public static string appletdashedittestmonialsjobtitlearabic {
            get {
                return ResourceManager.GetString("appletdashedittestmonialsjobtitlearabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client JobTitle in English.
        /// </summary>
        public static string appletdashedittestmonialsjobtitleenglish {
            get {
                return ResourceManager.GetString("appletdashedittestmonialsjobtitleenglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testmonial Publisher.
        /// </summary>
        public static string appletdashedittestmonialsPublisher {
            get {
                return ResourceManager.GetString("appletdashedittestmonialsPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question in Arabic.
        /// </summary>
        public static string appletdashedittestmonialsquestionarabic {
            get {
                return ResourceManager.GetString("appletdashedittestmonialsquestionarabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Question in English.
        /// </summary>
        public static string appletdashedittestmonialsquestionenglish {
            get {
                return ResourceManager.GetString("appletdashedittestmonialsquestionenglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/dashcss/basictable.css.
        /// </summary>
        public static string appletdashindexbaictablecss {
            get {
                return ResourceManager.GetString("appletdashindexbaictablecss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/dashcss/bootstrap.css.
        /// </summary>
        public static string appletdashindexbootstrapcss {
            get {
                return ResourceManager.GetString("appletdashindexbootstrapcss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string appletdashindexbootstraprtlcss {
            get {
                return ResourceManager.GetString("appletdashindexbootstraprtlcss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPLET Insight.
        /// </summary>
        public static string appletdashindexchartinsight {
            get {
                return ResourceManager.GetString("appletdashindexchartinsight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/dashcss/circles.css.
        /// </summary>
        public static string appletdashindexcirclecss {
            get {
                return ResourceManager.GetString("appletdashindexcirclecss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/dashcss/component.css.
        /// </summary>
        public static string appletdashindexcomponentcss {
            get {
                return ResourceManager.GetString("appletdashindexcomponentcss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/dashcss/export.css.
        /// </summary>
        public static string appletdashindexexportcss {
            get {
                return ResourceManager.GetString("appletdashindexexportcss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/dashcss/fileinput.min.css.
        /// </summary>
        public static string appletdashindexfileinputcss {
            get {
                return ResourceManager.GetString("appletdashindexfileinputcss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/dashcss/flipclock.css.
        /// </summary>
        public static string appletdashindexflipclockcss {
            get {
                return ResourceManager.GetString("appletdashindexflipclockcss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/dashcss/font-awesome.css.
        /// </summary>
        public static string appletdashindexfontawesomecss {
            get {
                return ResourceManager.GetString("appletdashindexfontawesomecss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800.
        /// </summary>
        public static string appletdashindexgooglefontcss {
            get {
                return ResourceManager.GetString("appletdashindexgooglefontcss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/images/logo.png.
        /// </summary>
        public static string appletdashindexlogoicon {
            get {
                return ResourceManager.GetString("appletdashindexlogoicon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/dashcss/newMedia.css.
        /// </summary>
        public static string appletdashindexnewmediacss {
            get {
                return ResourceManager.GetString("appletdashindexnewmediacss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/dashcss/newStyle.css.
        /// </summary>
        public static string appletdashindexnewstylecss {
            get {
                return ResourceManager.GetString("appletdashindexnewstylecss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string appletdashindexrecentclientscompany {
            get {
                return ResourceManager.GetString("appletdashindexrecentclientscompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string appletdashindexrecentclientsemail {
            get {
                return ResourceManager.GetString("appletdashindexrecentclientsemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fname.
        /// </summary>
        public static string appletdashindexrecentclientsfname {
            get {
                return ResourceManager.GetString("appletdashindexrecentclientsfname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lname.
        /// </summary>
        public static string appletdashindexrecentclientslname {
            get {
                return ResourceManager.GetString("appletdashindexrecentclientslname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneNumber.
        /// </summary>
        public static string appletdashindexrecentclientsphonenumber {
            get {
                return ResourceManager.GetString("appletdashindexrecentclientsphonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Clients.
        /// </summary>
        public static string appletdashindexrecentclientstitle {
            get {
                return ResourceManager.GetString("appletdashindexrecentclientstitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients Categories.
        /// </summary>
        public static string appletdashindexsidebarclientcategories {
            get {
                return ResourceManager.GetString("appletdashindexsidebarclientcategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string appletdashindexsidebarclients {
            get {
                return ResourceManager.GetString("appletdashindexsidebarclients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string appletdashindexsidebardashboard {
            get {
                return ResourceManager.GetString("appletdashindexsidebardashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Orders.
        /// </summary>
        public static string appletdashindexsidebardclientorders {
            get {
                return ResourceManager.GetString("appletdashindexsidebardclientorders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Category.
        /// </summary>
        public static string appletdashindexsidebardnewcategory {
            get {
                return ResourceManager.GetString("appletdashindexsidebardnewcategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New News.
        /// </summary>
        public static string appletdashindexsidebardnewnews {
            get {
                return ResourceManager.GetString("appletdashindexsidebardnewnews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        public static string appletdashindexsidebardnewproject {
            get {
                return ResourceManager.GetString("appletdashindexsidebardnewproject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string appletdashindexsidebardnews {
            get {
                return ResourceManager.GetString("appletdashindexsidebardnews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Categories.
        /// </summary>
        public static string appletdashindexsidebardnewscategories {
            get {
                return ResourceManager.GetString("appletdashindexsidebardnewscategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects Categories.
        /// </summary>
        public static string appletdashindexsidebardprojectcategories {
            get {
                return ResourceManager.GetString("appletdashindexsidebardprojectcategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string appletdashindexsidebardprojects {
            get {
                return ResourceManager.GetString("appletdashindexsidebardprojects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managers.
        /// </summary>
        public static string appletdashindexsidebarmanagers {
            get {
                return ResourceManager.GetString("appletdashindexsidebarmanagers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Client.
        /// </summary>
        public static string appletdashindexsidebarnewclient {
            get {
                return ResourceManager.GetString("appletdashindexsidebarnewclient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Manager.
        /// </summary>
        public static string appletdashindexsidebarnewmanager {
            get {
                return ResourceManager.GetString("appletdashindexsidebarnewmanager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Plans.
        /// </summary>
        public static string appletdashindexsidebarnewplans {
            get {
                return ResourceManager.GetString("appletdashindexsidebarnewplans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Team.
        /// </summary>
        public static string appletdashindexsidebarnewteam {
            get {
                return ResourceManager.GetString("appletdashindexsidebarnewteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Testimonial.
        /// </summary>
        public static string appletdashindexsidebarnewtestimonial {
            get {
                return ResourceManager.GetString("appletdashindexsidebarnewtestimonial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plans Categories.
        /// </summary>
        public static string appletdashindexsidebarplancategories {
            get {
                return ResourceManager.GetString("appletdashindexsidebarplancategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plans.
        /// </summary>
        public static string appletdashindexsidebarplans {
            get {
                return ResourceManager.GetString("appletdashindexsidebarplans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string appletdashindexsidebarreports {
            get {
                return ResourceManager.GetString("appletdashindexsidebarreports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        public static string appletdashindexsidebarteams {
            get {
                return ResourceManager.GetString("appletdashindexsidebarteams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams Categories.
        /// </summary>
        public static string appletdashindexsidebarteamscategories {
            get {
                return ResourceManager.GetString("appletdashindexsidebarteamscategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testimonials Categories.
        /// </summary>
        public static string appletdashindexsidebartestimonialcategories {
            get {
                return ResourceManager.GetString("appletdashindexsidebartestimonialcategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testimonials.
        /// </summary>
        public static string appletdashindexsidebartestimonials {
            get {
                return ResourceManager.GetString("appletdashindexsidebartestimonials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/dashcss/style.css.
        /// </summary>
        public static string appletdashindexstylecss {
            get {
                return ResourceManager.GetString("appletdashindexstylecss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/dashcss/style_grid.css.
        /// </summary>
        public static string appletdashindexstylegridcss {
            get {
                return ResourceManager.GetString("appletdashindexstylegridcss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/dashcss/table-style.css.
        /// </summary>
        public static string appletdashindexstyletablecss {
            get {
                return ResourceManager.GetString("appletdashindexstyletablecss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/dashcss/jquery.toast.min.css.
        /// </summary>
        public static string appletdashindextoastcss {
            get {
                return ResourceManager.GetString("appletdashindextoastcss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPLET.
        /// </summary>
        public static string appletdashindextopmenuappletbrand {
            get {
                return ResourceManager.GetString("appletdashindextopmenuappletbrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عربى.
        /// </summary>
        public static string appletdashindextopmenulanguage {
            get {
                return ResourceManager.GetString("appletdashindextopmenulanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See all Pending Messages.
        /// </summary>
        public static string appletdashindextopmenumessagesseeall {
            get {
                return ResourceManager.GetString("appletdashindextopmenumessagesseeall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPLET Messages.
        /// </summary>
        public static string appletdashindextopmenumessagestitle {
            get {
                return ResourceManager.GetString("appletdashindextopmenumessagestitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See all pending NewsLetters.
        /// </summary>
        public static string appletdashindextopmenunewslettersseeall {
            get {
                return ResourceManager.GetString("appletdashindextopmenunewslettersseeall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPLET Newsletters.
        /// </summary>
        public static string appletdashindextopmenunewsletterstitle {
            get {
                return ResourceManager.GetString("appletdashindextopmenunewsletterstitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See all Notifications.
        /// </summary>
        public static string appletdashindextopmenunotificationsseeall {
            get {
                return ResourceManager.GetString("appletdashindextopmenunotificationsseeall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPLET Notifications.
        /// </summary>
        public static string appletdashindextopmenunotificationstitle {
            get {
                return ResourceManager.GetString("appletdashindextopmenunotificationstitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string appletdashindextopmenuprofile {
            get {
                return ResourceManager.GetString("appletdashindextopmenuprofile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string appletdashindextopmenuprologout {
            get {
                return ResourceManager.GetString("appletdashindextopmenuprologout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search about your word .
        /// </summary>
        public static string appletdashindextopmenusearchplaceholder {
            get {
                return ResourceManager.GetString("appletdashindextopmenusearchplaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managers Report.
        /// </summary>
        public static string appletdashmanagersreport {
            get {
                return ResourceManager.GetString("appletdashmanagersreport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Description in Arabic.
        /// </summary>
        public static string appletdashnewcategorydescriptionar {
            get {
                return ResourceManager.GetString("appletdashnewcategorydescriptionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Description in English.
        /// </summary>
        public static string appletdashnewcategorydescriptionen {
            get {
                return ResourceManager.GetString("appletdashnewcategorydescriptionen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Category Name in Arabic.
        /// </summary>
        public static string appletdashnewcategorynamear {
            get {
                return ResourceManager.GetString("appletdashnewcategorynamear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Category Name in English.
        /// </summary>
        public static string appletdashnewcategorynameen {
            get {
                return ResourceManager.GetString("appletdashnewcategorynameen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New News.
        /// </summary>
        public static string appletdashnewnewsbreadcrums {
            get {
                return ResourceManager.GetString("appletdashnewnewsbreadcrums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Long in Arabic.
        /// </summary>
        public static string appletdashnewnewsplaceholderlongarabic {
            get {
                return ResourceManager.GetString("appletdashnewnewsplaceholderlongarabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Long in English.
        /// </summary>
        public static string appletdashnewnewsplaceholderlongenglish {
            get {
                return ResourceManager.GetString("appletdashnewnewsplaceholderlongenglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Short in Arabic.
        /// </summary>
        public static string appletdashnewnewsplaceholdershortearabic {
            get {
                return ResourceManager.GetString("appletdashnewnewsplaceholdershortearabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Short in English.
        /// </summary>
        public static string appletdashnewnewsplaceholdershortenglish {
            get {
                return ResourceManager.GetString("appletdashnewnewsplaceholdershortenglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Title in Arabic.
        /// </summary>
        public static string appletdashnewnewsplaceholdertitleinarabic {
            get {
                return ResourceManager.GetString("appletdashnewnewsplaceholdertitleinarabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Title in English.
        /// </summary>
        public static string appletdashnewnewsplaceholdertitleinenglish {
            get {
                return ResourceManager.GetString("appletdashnewnewsplaceholdertitleinenglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Select Project Category -.
        /// </summary>
        public static string appletdashnewprojectplaceholdercategory {
            get {
                return ResourceManager.GetString("appletdashnewprojectplaceholdercategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name in Arabic.
        /// </summary>
        public static string appletdashnewprojectplaceholdernamearabic {
            get {
                return ResourceManager.GetString("appletdashnewprojectplaceholdernamearabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name in English .
        /// </summary>
        public static string appletdashnewprojectplaceholdernameenglish {
            get {
                return ResourceManager.GetString("appletdashnewprojectplaceholdernameenglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project URL.
        /// </summary>
        public static string appletdashnewprojectplaceholderurl {
            get {
                return ResourceManager.GetString("appletdashnewprojectplaceholderurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready?.
        /// </summary>
        public static string appletdashnewprojectreadybutton {
            get {
                return ResourceManager.GetString("appletdashnewprojectreadybutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string appletdashnewprojectsavebutton {
            get {
                return ResourceManager.GetString("appletdashnewprojectsavebutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        public static string appletdashnewprojecttitle {
            get {
                return ResourceManager.GetString("appletdashnewprojecttitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Publisher.
        /// </summary>
        public static string appletdashnewsplaceholderseacbypublisher {
            get {
                return ResourceManager.GetString("appletdashnewsplaceholderseacbypublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by title.
        /// </summary>
        public static string appletdashnewsplaceholderseacbytitle {
            get {
                return ResourceManager.GetString("appletdashnewsplaceholderseacbytitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Report.
        /// </summary>
        public static string appletdashnewsreport {
            get {
                return ResourceManager.GetString("appletdashnewsreport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string appletdashnewstitle {
            get {
                return ResourceManager.GetString("appletdashnewstitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name in Arabic.
        /// </summary>
        public static string appletdashnewteamfnamear {
            get {
                return ResourceManager.GetString("appletdashnewteamfnamear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name in English.
        /// </summary>
        public static string appletdashnewteamfnameen {
            get {
                return ResourceManager.GetString("appletdashnewteamfnameen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Email.
        /// </summary>
        public static string appletdashnewteamhemail {
            get {
                return ResourceManager.GetString("appletdashnewteamhemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title in Arabic.
        /// </summary>
        public static string appletdashnewteamhjobtitlear {
            get {
                return ResourceManager.GetString("appletdashnewteamhjobtitlear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title in English.
        /// </summary>
        public static string appletdashnewteamhjobtitleen {
            get {
                return ResourceManager.GetString("appletdashnewteamhjobtitleen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name in Arabic.
        /// </summary>
        public static string appletdashnewteamlnamear {
            get {
                return ResourceManager.GetString("appletdashnewteamlnamear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name in English.
        /// </summary>
        public static string appletdashnewteamlnameen {
            get {
                return ResourceManager.GetString("appletdashnewteamlnameen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Phone Number.
        /// </summary>
        public static string appletdashnewteamphonenumber {
            get {
                return ResourceManager.GetString("appletdashnewteamphonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Salary.
        /// </summary>
        public static string appletdashnewteamsalary {
            get {
                return ResourceManager.GetString("appletdashnewteamsalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Description in English.
        /// </summary>
        public static string appletdashplansdescriptionarabic {
            get {
                return ResourceManager.GetString("appletdashplansdescriptionarabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Description in English.
        /// </summary>
        public static string appletdashplansdescriptionenglish {
            get {
                return ResourceManager.GetString("appletdashplansdescriptionenglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Name in Arabic.
        /// </summary>
        public static string appletdashplansnamearabic {
            get {
                return ResourceManager.GetString("appletdashplansnamearabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Name in English.
        /// </summary>
        public static string appletdashplansnameenglish {
            get {
                return ResourceManager.GetString("appletdashplansnameenglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Price .
        /// </summary>
        public static string appletdashplansprice {
            get {
                return ResourceManager.GetString("appletdashplansprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plans Report.
        /// </summary>
        public static string appletdashplansreport {
            get {
                return ResourceManager.GetString("appletdashplansreport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Plan Name Arabic.
        /// </summary>
        public static string appletdashplanssearchbyplannamearabic {
            get {
                return ResourceManager.GetString("appletdashplanssearchbyplannamearabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Plan Name.
        /// </summary>
        public static string appletdashplanssearchbyplannameenglish {
            get {
                return ResourceManager.GetString("appletdashplanssearchbyplannameenglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        public static string appletdashprojectcategoriespublisher {
            get {
                return ResourceManager.GetString("appletdashprojectcategoriespublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Category Name in Arabic.
        /// </summary>
        public static string appletdashprojectcategoriessearchbynamear {
            get {
                return ResourceManager.GetString("appletdashprojectcategoriessearchbynamear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Category Name in English.
        /// </summary>
        public static string appletdashprojectcategoriessearchbynameen {
            get {
                return ResourceManager.GetString("appletdashprojectcategoriessearchbynameen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string appletdashprojectsadd {
            get {
                return ResourceManager.GetString("appletdashprojectsadd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string appletdashprojectscategory {
            get {
                return ResourceManager.GetString("appletdashprojectscategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime.
        /// </summary>
        public static string appletdashprojectsdatetime {
            get {
                return ResourceManager.GetString("appletdashprojectsdatetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string appletdashprojectsdelete {
            get {
                return ResourceManager.GetString("appletdashprojectsdelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string appletdashprojectsedit {
            get {
                return ResourceManager.GetString("appletdashprojectsedit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string appletdashprojectsimage {
            get {
                return ResourceManager.GetString("appletdashprojectsimage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string appletdashprojectsname {
            get {
                return ResourceManager.GetString("appletdashprojectsname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects Report.
        /// </summary>
        public static string appletdashprojectsreport {
            get {
                return ResourceManager.GetString("appletdashprojectsreport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Select Category -.
        /// </summary>
        public static string appletdashprojectssearchbycategoryname {
            get {
                return ResourceManager.GetString("appletdashprojectssearchbycategoryname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Project Name.
        /// </summary>
        public static string appletdashprojectssearchbyprojectname {
            get {
                return ResourceManager.GetString("appletdashprojectssearchbyprojectname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Project URL.
        /// </summary>
        public static string appletdashprojectssearchbyprojecturl {
            get {
                return ResourceManager.GetString("appletdashprojectssearchbyprojecturl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string appletdashprojectsurl {
            get {
                return ResourceManager.GetString("appletdashprojectsurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seen.
        /// </summary>
        public static string appletdashseen {
            get {
                return ResourceManager.GetString("appletdashseen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string appletdashteamsemail {
            get {
                return ResourceManager.GetString("appletdashteamsemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fname.
        /// </summary>
        public static string appletdashteamsfname {
            get {
                return ResourceManager.GetString("appletdashteamsfname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lname.
        /// </summary>
        public static string appletdashteamslname {
            get {
                return ResourceManager.GetString("appletdashteamslname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string appletdashteamsphone {
            get {
                return ResourceManager.GetString("appletdashteamsphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams Report.
        /// </summary>
        public static string appletdashteamsreport {
            get {
                return ResourceManager.GetString("appletdashteamsreport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Name.
        /// </summary>
        public static string appletdashteamssearchbyname {
            get {
                return ResourceManager.GetString("appletdashteamssearchbyname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by  Phone Number.
        /// </summary>
        public static string appletdashteamssearchbyphonenumber {
            get {
                return ResourceManager.GetString("appletdashteamssearchbyphonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testmonial Question in Arabic.
        /// </summary>
        public static string appletdashtestmonialanswerarabic {
            get {
                return ResourceManager.GetString("appletdashtestmonialanswerarabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testmonial Answer in English.
        /// </summary>
        public static string appletdashtestmonialanswerenglish {
            get {
                return ResourceManager.GetString("appletdashtestmonialanswerenglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Name in Arabic.
        /// </summary>
        public static string appletdashtestmonialclientnamearabic {
            get {
                return ResourceManager.GetString("appletdashtestmonialclientnamearabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Name in English.
        /// </summary>
        public static string appletdashtestmonialclientnameenglish {
            get {
                return ResourceManager.GetString("appletdashtestmonialclientnameenglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testmonial Question in Arabic.
        /// </summary>
        public static string appletdashtestmonialquestionarabic {
            get {
                return ResourceManager.GetString("appletdashtestmonialquestionarabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testmonial Question in English.
        /// </summary>
        public static string appletdashtestmonialquestionenglish {
            get {
                return ResourceManager.GetString("appletdashtestmonialquestionenglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JobTitle in Arabic.
        /// </summary>
        public static string appletdashtestmonialsjobtitlearabic {
            get {
                return ResourceManager.GetString("appletdashtestmonialsjobtitlearabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JobTitle in English.
        /// </summary>
        public static string appletdashtestmonialsjobtitleenglish {
            get {
                return ResourceManager.GetString("appletdashtestmonialsjobtitleenglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string appletdashtestmonialsquestion {
            get {
                return ResourceManager.GetString("appletdashtestmonialsquestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Client Name.
        /// </summary>
        public static string appletdashtestmonialssearchbyclientname {
            get {
                return ResourceManager.GetString("appletdashtestmonialssearchbyclientname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Testmonial Question.
        /// </summary>
        public static string appletdashtestmonialssearchbyquestion {
            get {
                return ResourceManager.GetString("appletdashtestmonialssearchbyquestion", resourceCulture);
            }
        }
    }
}
