//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appletindex {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppletSoftware.App_GlobalResources.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launching the client&apos;s hand in adapting the programs to suit his needs without the need for company intervention.
        /// </summary>
        public static string appletaboutusclientparagraph {
            get {
                return ResourceManager.GetString("appletaboutusclientparagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string appletaboutusclienttitle {
            get {
                return ResourceManager.GetString("appletaboutusclienttitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string appletaboutuscontactusbutton {
            get {
                return ResourceManager.GetString("appletaboutuscontactusbutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy to develop, link and update applications to meet the evolution of activity and changing needs.
        /// </summary>
        public static string appletaboutusdevelopmentparagraph {
            get {
                return ResourceManager.GetString("appletaboutusdevelopmentparagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development.
        /// </summary>
        public static string appletaboutusdevelopmenttitle {
            get {
                return ResourceManager.GetString("appletaboutusdevelopmenttitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReachUpSoftware was founded in 2017. Since then, the company has been providing the best support in the field of building and designing programs and websites to provide solutions of a distinctive nature by using the latest technology and follow up everything that is new in the world of design, programming and development to maintain the forefront and enjoy the advantages of technology To obtain maximum customer satisfaction. ReachUpSoftware is one of the largest Arab companies in the field of the Internet t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string appletaboutusmissionparagrph1 {
            get {
                return ResourceManager.GetString("appletaboutusmissionparagrph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you already own a website we would be happy to develop it for you either if you do not have a website, we are honored to build your site. If you need a program to run your business, such as supermarket management program or coffee ..... etc, whatever the nature of your activity we have your request, God willing, and the highest specifications and the latest techniques..
        /// </summary>
        public static string appletaboutusmissionparagrph2 {
            get {
                return ResourceManager.GetString("appletaboutusmissionparagrph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We Are Happy To Help You.
        /// </summary>
        public static string appletaboutusmissiontitle {
            get {
                return ResourceManager.GetString("appletaboutusmissiontitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you believe in your ability to change cultures and make the world a better place to do, this is what we are trying to do with high quality products that carry the values that we influence in society..
        /// </summary>
        public static string appletaboutusparagraph {
            get {
                return ResourceManager.GetString("appletaboutusparagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide more flexible solutions to meet the different needs of customers within the same activity.
        /// </summary>
        public static string appletaboutussolutionparagraph {
            get {
                return ResourceManager.GetString("appletaboutussolutionparagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution.
        /// </summary>
        public static string appletaboutussolutiontitle {
            get {
                return ResourceManager.GetString("appletaboutussolutiontitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string appletaboutustitle {
            get {
                return ResourceManager.GetString("appletaboutustitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/css/slick/ajax-loader.gif.
        /// </summary>
        public static string appletajaxloadericon {
            get {
                return ResourceManager.GetString("appletajaxloadericon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/css/animate.min.css.
        /// </summary>
        public static string appletanimatecss {
            get {
                return ResourceManager.GetString("appletanimatecss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/css/bootstrap.min.css.
        /// </summary>
        public static string appletbootstrapcss {
            get {
                return ResourceManager.GetString("appletbootstrapcss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string appletbootstraprtlcss {
            get {
                return ResourceManager.GetString("appletbootstraprtlcss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عربى.
        /// </summary>
        public static string appletchangelanguagebutton {
            get {
                return ResourceManager.GetString("appletchangelanguagebutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/css/jquery.fancybox.min.css.
        /// </summary>
        public static string appletfancyboxcss {
            get {
                return ResourceManager.GetString("appletfancyboxcss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/css/font-awesome.min.css.
        /// </summary>
        public static string appletfontawesomcss {
            get {
                return ResourceManager.GetString("appletfontawesomcss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://fonts.googleapis.com/css?family=Titillium+Web:400,200,200italic,300,300italic,400italic,600,600italic,700,700italic,900.
        /// </summary>
        public static string appletgooglefonts {
            get {
                return ResourceManager.GetString("appletgooglefonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800.
        /// </summary>
        public static string appletgooglefonts2 {
            get {
                return ResourceManager.GetString("appletgooglefonts2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/css/hover-min.css.
        /// </summary>
        public static string applethovercss {
            get {
                return ResourceManager.GetString("applethovercss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/css/icon-close-white.png.
        /// </summary>
        public static string appleticoncloseicon {
            get {
                return ResourceManager.GetString("appleticoncloseicon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string appletindexcontactusemail {
            get {
                return ResourceManager.GetString("appletindexcontactusemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info@reachup.com.
        /// </summary>
        public static string appletindexcontactusemailvalue {
            get {
                return ResourceManager.GetString("appletindexcontactusemailvalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        public static string appletindexcontactusinfoaddress {
            get {
                return ResourceManager.GetString("appletindexcontactusinfoaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kolayet Adab Street  - Mansoura - Dakahlia Governorate -Egypt.
        /// </summary>
        public static string appletindexcontactusinfoaddressvalue {
            get {
                return ResourceManager.GetString("appletindexcontactusinfoaddressvalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone:.
        /// </summary>
        public static string appletindexcontactusinfophone {
            get {
                return ResourceManager.GetString("appletindexcontactusinfophone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +201016740846 - +201016740846  .
        /// </summary>
        public static string appletindexcontactusinfophonevalue {
            get {
                return ResourceManager.GetString("appletindexcontactusinfophonevalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string appletindexcontactusplaceholderemail {
            get {
                return ResourceManager.GetString("appletindexcontactusplaceholderemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Message *.
        /// </summary>
        public static string appletindexcontactusplaceholdermessage {
            get {
                return ResourceManager.GetString("appletindexcontactusplaceholdermessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string appletindexcontactusplaceholdersubject {
            get {
                return ResourceManager.GetString("appletindexcontactusplaceholdersubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Now.
        /// </summary>
        public static string appletindexcontactussendbutton {
            get {
                return ResourceManager.GetString("appletindexcontactussendbutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will contact you by your Email and our team will reply to your Message ..
        /// </summary>
        public static string appletindexcontactussmallhint {
            get {
                return ResourceManager.GetString("appletindexcontactussmallhint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get in touch with us!.
        /// </summary>
        public static string appletindexcontactustitle {
            get {
                return ResourceManager.GetString("appletindexcontactustitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPS.
        /// </summary>
        public static string appletindexcounterapps {
            get {
                return ResourceManager.GetString("appletindexcounterapps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string appletindexcounterclients {
            get {
                return ResourceManager.GetString("appletindexcounterclients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLans.
        /// </summary>
        public static string appletindexcounterplans {
            get {
                return ResourceManager.GetString("appletindexcounterplans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testmonials.
        /// </summary>
        public static string appletindexcountertestmonials {
            get {
                return ResourceManager.GetString("appletindexcountertestmonials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our core expertise lies in connecting your brand to your business with the great opportunities the web offers. Creative branding of your brand involves your website in an integrated process to enhance your presence among competitors. ReachUp is designed for elegance, simplicity and clarity, with an emphasis on improving the user experience for our applications.
        /// </summary>
        public static string appletindexfooteraboutparagraph {
            get {
                return ResourceManager.GetString("appletindexfooteraboutparagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About ReachUp Agency.
        /// </summary>
        public static string appletindexfooterabouttitle {
            get {
                return ResourceManager.GetString("appletindexfooterabouttitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReachUp Agency.
        /// </summary>
        public static string appletindexfooterbrand {
            get {
                return ResourceManager.GetString("appletindexfooterbrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2020 by.
        /// </summary>
        public static string appletindexfootercopyright {
            get {
                return ResourceManager.GetString("appletindexfootercopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mock Up.
        /// </summary>
        public static string appletindexfooterdemos {
            get {
                return ResourceManager.GetString("appletindexfooterdemos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string appletindexfooterquicklinksli1 {
            get {
                return ResourceManager.GetString("appletindexfooterquicklinksli1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plans.
        /// </summary>
        public static string appletindexfooterquicklinksli2 {
            get {
                return ResourceManager.GetString("appletindexfooterquicklinksli2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string appletindexfooterquicklinksli3 {
            get {
                return ResourceManager.GetString("appletindexfooterquicklinksli3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string appletindexfooterquicklinksli4 {
            get {
                return ResourceManager.GetString("appletindexfooterquicklinksli4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string appletindexfooterquicklinksli5 {
            get {
                return ResourceManager.GetString("appletindexfooterquicklinksli5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string appletindexfooterquicklinksli6 {
            get {
                return ResourceManager.GetString("appletindexfooterquicklinksli6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string appletindexfooterquicklinksli7 {
            get {
                return ResourceManager.GetString("appletindexfooterquicklinksli7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Links.
        /// </summary>
        public static string appletindexfooterquicklinkstitle {
            get {
                return ResourceManager.GetString("appletindexfooterquicklinkstitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flexible solutions to meet customers needs .
        /// </summary>
        public static string appletindexhowitworksmenuli1 {
            get {
                return ResourceManager.GetString("appletindexhowitworksmenuli1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build confidence through good technical support.
        /// </summary>
        public static string appletindexhowitworksmenuli2 {
            get {
                return ResourceManager.GetString("appletindexhowitworksmenuli2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapting the programs to suit client needs.
        /// </summary>
        public static string appletindexhowitworksmenuli3 {
            get {
                return ResourceManager.GetString("appletindexhowitworksmenuli3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy to develop and update applications.
        /// </summary>
        public static string appletindexhowitworksmenuli4 {
            get {
                return ResourceManager.GetString("appletindexhowitworksmenuli4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scalability applications for modernization.
        /// </summary>
        public static string appletindexhowitworksmenuli5 {
            get {
                return ResourceManager.GetString("appletindexhowitworksmenuli5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How It Works.
        /// </summary>
        public static string appletindexhowitworkstitle {
            get {
                return ResourceManager.GetString("appletindexhowitworkstitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Email Here.
        /// </summary>
        public static string appletindexnewsletterstemailplaceholder {
            get {
                return ResourceManager.GetString("appletindexnewsletterstemailplaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewsLetters.
        /// </summary>
        public static string appletindexnewsletterstitle {
            get {
                return ResourceManager.GetString("appletindexnewsletterstitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Latest news and offers of ReachUpover  24 Hours.
        /// </summary>
        public static string appletindexnewsletterstsmallhint {
            get {
                return ResourceManager.GetString("appletindexnewsletterstsmallhint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read More.
        /// </summary>
        public static string appletindexnewsreadmore {
            get {
                return ResourceManager.GetString("appletindexnewsreadmore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show More.
        /// </summary>
        public static string appletindexnewsshowmore {
            get {
                return ResourceManager.GetString("appletindexnewsshowmore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our News.
        /// </summary>
        public static string appletindexnewstitle {
            get {
                return ResourceManager.GetString("appletindexnewstitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional.
        /// </summary>
        public static string appletindexourfeaturesli1 {
            get {
                return ResourceManager.GetString("appletindexourfeaturesli1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trustworthy.
        /// </summary>
        public static string appletindexourfeaturesli2 {
            get {
                return ResourceManager.GetString("appletindexourfeaturesli2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendly.
        /// </summary>
        public static string appletindexourfeaturesli3 {
            get {
                return ResourceManager.GetString("appletindexourfeaturesli3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efficient.
        /// </summary>
        public static string appletindexourfeaturesli4 {
            get {
                return ResourceManager.GetString("appletindexourfeaturesli4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valuable Partner.
        /// </summary>
        public static string appletindexourfeaturesli5 {
            get {
                return ResourceManager.GetString("appletindexourfeaturesli5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accurate.
        /// </summary>
        public static string appletindexourfeaturesli6 {
            get {
                return ResourceManager.GetString("appletindexourfeaturesli6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interesting.
        /// </summary>
        public static string appletindexourfeaturesli7 {
            get {
                return ResourceManager.GetString("appletindexourfeaturesli7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reusable.
        /// </summary>
        public static string appletindexourfeaturesli8 {
            get {
                return ResourceManager.GetString("appletindexourfeaturesli8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Features.
        /// </summary>
        public static string appletindexourfeaturestitle {
            get {
                return ResourceManager.GetString("appletindexourfeaturestitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order this Plan.
        /// </summary>
        public static string appletindexplansorderplan {
            get {
                return ResourceManager.GetString("appletindexplansorderplan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show More.
        /// </summary>
        public static string appletindexplansshowmore {
            get {
                return ResourceManager.GetString("appletindexplansshowmore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing Plans.
        /// </summary>
        public static string appletindexplanstitle {
            get {
                return ResourceManager.GetString("appletindexplanstitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show More.
        /// </summary>
        public static string appletindexprojectsshowmore {
            get {
                return ResourceManager.GetString("appletindexprojectsshowmore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Projects.
        /// </summary>
        public static string appletindexprojectstitle {
            get {
                return ResourceManager.GetString("appletindexprojectstitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special programming services,  Programming of Web and Desktop applications..
        /// </summary>
        public static string appletindexservicesboxesdevelopmentparagrapg {
            get {
                return ResourceManager.GetString("appletindexservicesboxesdevelopmentparagrapg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development.
        /// </summary>
        public static string appletindexservicesboxesdevelopmenttitle {
            get {
                return ResourceManager.GetString("appletindexservicesboxesdevelopmenttitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build a strong relationship with your audience and fans through a strategic planning for your social networks.
        /// </summary>
        public static string appletindexservicesboxesdigitalmarketingparagraph {
            get {
                return ResourceManager.GetString("appletindexservicesboxesdigitalmarketingparagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Marketing.
        /// </summary>
        public static string appletindexservicesboxesdigitalmarketingtitle {
            get {
                return ResourceManager.GetString("appletindexservicesboxesdigitalmarketingtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating your motion graphics with attractive visuals and interactive animations.
        /// </summary>
        public static string appletindexservicesboxesgraphicsparagraph {
            get {
                return ResourceManager.GetString("appletindexservicesboxesgraphicsparagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphic Design.
        /// </summary>
        public static string appletindexservicesboxesgraphicstitle {
            get {
                return ResourceManager.GetString("appletindexservicesboxesgraphicstitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud hosting services, servers, VPS, domain reservation services and technical support for hosting.
        /// </summary>
        public static string appletindexservicesboxeshostingdomainsparagraph {
            get {
                return ResourceManager.GetString("appletindexservicesboxeshostingdomainsparagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hosting &amp; Domains.
        /// </summary>
        public static string appletindexservicesboxeshostingdomainstitle {
            get {
                return ResourceManager.GetString("appletindexservicesboxeshostingdomainstitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We provide mobile application programming services for Android, IOS , Windows Phone.
        /// </summary>
        public static string appletindexservicesboxesmobileappparagrapg {
            get {
                return ResourceManager.GetString("appletindexservicesboxesmobileappparagrapg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile App.
        /// </summary>
        public static string appletindexservicesboxesmobileapptitle {
            get {
                return ResourceManager.GetString("appletindexservicesboxesmobileapptitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web design services, printed identity and design of mobile application interfaces..
        /// </summary>
        public static string appletindexservicesboxeswebdesignparagrapg {
            get {
                return ResourceManager.GetString("appletindexservicesboxeswebdesignparagrapg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Design.
        /// </summary>
        public static string appletindexservicesboxeswebdesigntitle {
            get {
                return ResourceManager.GetString("appletindexservicesboxeswebdesigntitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our core expertise lies in connecting your brand to your business with the great opportunities the web offers.
        ///                        Creative branding of your brand involves your website in an integrated process to enhance your presence among competitors.
        ///                        &lt;span class=&quot;emphase&quot;&gt;ReachUp&lt;/span&gt; is designed for elegance, simplicity and clarity, with an emphasis on improving the user experience for our applications..
        /// </summary>
        public static string appletindexservicesparagraph {
            get {
                return ResourceManager.GetString("appletindexservicesparagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string appletindexservicestitle {
            get {
                return ResourceManager.GetString("appletindexservicestitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show More.
        /// </summary>
        public static string appletindexteamshowmore {
            get {
                return ResourceManager.GetString("appletindexteamshowmore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEET THE TEAM.
        /// </summary>
        public static string appletindexteamtitle {
            get {
                return ResourceManager.GetString("appletindexteamtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/css/ionicons.min.css.
        /// </summary>
        public static string appletioniconscss {
            get {
                return ResourceManager.GetString("appletioniconscss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/css/linearicons.css.
        /// </summary>
        public static string appletlineariconcss {
            get {
                return ResourceManager.GetString("appletlineariconcss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Home.
        /// </summary>
        public static string appletloginbacktohome {
            get {
                return ResourceManager.GetString("appletloginbacktohome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string appletloginemailplaceholder {
            get {
                return ResourceManager.GetString("appletloginemailplaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        public static string appletloginhaveanaccount {
            get {
                return ResourceManager.GetString("appletloginhaveanaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string appletloginpasswordplaceholder {
            get {
                return ResourceManager.GetString("appletloginpasswordplaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string appletloginsigninbutton {
            get {
                return ResourceManager.GetString("appletloginsigninbutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string appletloginsignintitle {
            get {
                return ResourceManager.GetString("appletloginsignintitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/images/logo.png.
        /// </summary>
        public static string appletlogoicon {
            get {
                return ResourceManager.GetString("appletlogoicon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/css/media.css.
        /// </summary>
        public static string appletmediacss {
            get {
                return ResourceManager.GetString("appletmediacss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string appletmybackgroundfeatures {
            get {
                return ResourceManager.GetString("appletmybackgroundfeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Start.
        /// </summary>
        public static string appletmybackgroundgetstart {
            get {
                return ResourceManager.GetString("appletmybackgroundgetstart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Design Services.
        /// </summary>
        public static string appletmybackgroundtyped1 {
            get {
                return ResourceManager.GetString("appletmybackgroundtyped1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Development Services.
        /// </summary>
        public static string appletmybackgroundtyped2 {
            get {
                return ResourceManager.GetString("appletmybackgroundtyped2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile App Services.
        /// </summary>
        public static string appletmybackgroundtyped3 {
            get {
                return ResourceManager.GetString("appletmybackgroundtyped3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Marketing Services.
        /// </summary>
        public static string appletmybackgroundtyped4 {
            get {
                return ResourceManager.GetString("appletmybackgroundtyped4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion Graphics Services.
        /// </summary>
        public static string appletmybackgroundtyped5 {
            get {
                return ResourceManager.GetString("appletmybackgroundtyped5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hosting &amp;Domains Services.
        /// </summary>
        public static string appletmybackgroundtyped6 {
            get {
                return ResourceManager.GetString("appletmybackgroundtyped6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days ago.
        /// </summary>
        public static string appletnewsdetailsdaysago {
            get {
                return ResourceManager.GetString("appletnewsdetailsdaysago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted by.
        /// </summary>
        public static string appletnewsdetailspostedby {
            get {
                return ResourceManager.GetString("appletnewsdetailspostedby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill Order Form.
        /// </summary>
        public static string appletordernowfillform {
            get {
                return ResourceManager.GetString("appletordernowfillform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email (Required) *.
        /// </summary>
        public static string appletordernoworderemaillabel {
            get {
                return ResourceManager.GetString("appletordernoworderemaillabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name (Required) *.
        /// </summary>
        public static string appletordernoworderfirstnamelabel {
            get {
                return ResourceManager.GetString("appletordernoworderfirstnamelabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name (Required) *.
        /// </summary>
        public static string appletordernoworderlastnamelabel {
            get {
                return ResourceManager.GetString("appletordernoworderlastnamelabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message(Required) *.
        /// </summary>
        public static string appletordernowordermessageelabel {
            get {
                return ResourceManager.GetString("appletordernowordermessageelabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number (Required) *.
        /// </summary>
        public static string appletordernoworderphonenumberlabel {
            get {
                return ResourceManager.GetString("appletordernoworderphonenumberlabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Plan *.
        /// </summary>
        public static string appletordernoworderplanlabel {
            get {
                return ResourceManager.GetString("appletordernoworderplanlabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string appletordernowsubmitbutton {
            get {
                return ResourceManager.GetString("appletordernowsubmitbutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/css/popuo-box.css.
        /// </summary>
        public static string appletpopupboxcss {
            get {
                return ResourceManager.GetString("appletpopupboxcss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/css/post.css.
        /// </summary>
        public static string appletpostscss {
            get {
                return ResourceManager.GetString("appletpostscss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/css/slick/slick.css.
        /// </summary>
        public static string appletslickcss {
            get {
                return ResourceManager.GetString("appletslickcss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/css/slick/slick-theme.css.
        /// </summary>
        public static string appletslickthemecss {
            get {
                return ResourceManager.GetString("appletslickthemecss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/css/style2.css.
        /// </summary>
        public static string appletstyle2css {
            get {
                return ResourceManager.GetString("appletstyle2css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/css/style.css.
        /// </summary>
        public static string appletstylecss {
            get {
                return ResourceManager.GetString("appletstylecss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReachUpTeam is working for you.
        /// </summary>
        public static string appletteamtitle {
            get {
                return ResourceManager.GetString("appletteamtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/css/themify-icons.css.
        /// </summary>
        public static string appletthemifycss {
            get {
                return ResourceManager.GetString("appletthemifycss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string applettopmenuabout {
            get {
                return ResourceManager.GetString("applettopmenuabout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string applettopmenublog {
            get {
                return ResourceManager.GetString("applettopmenublog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string applettopmenucontact {
            get {
                return ResourceManager.GetString("applettopmenucontact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string applettopmenuhome {
            get {
                return ResourceManager.GetString("applettopmenuhome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string applettopmenulogin {
            get {
                return ResourceManager.GetString("applettopmenulogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string applettopmenulogoff {
            get {
                return ResourceManager.GetString("applettopmenulogoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plans.
        /// </summary>
        public static string applettopmenuplans {
            get {
                return ResourceManager.GetString("applettopmenuplans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string applettopmenuprojects {
            get {
                return ResourceManager.GetString("applettopmenuprojects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string applettopmenuservices {
            get {
                return ResourceManager.GetString("applettopmenuservices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string applettopmenuteams {
            get {
                return ResourceManager.GetString("applettopmenuteams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/css/grt-youtube-popup.css.
        /// </summary>
        public static string appletyoutubepopupcss {
            get {
                return ResourceManager.GetString("appletyoutubepopupcss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/css/YouTubePopUp.css.
        /// </summary>
        public static string appletyoutubepopupvimocss {
            get {
                return ResourceManager.GetString("appletyoutubepopupvimocss", resourceCulture);
            }
        }
    }
}
