//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppletSoftware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUsersInfoPlu
    {
        public string UInfoPlus_Id { get; set; }
        public string UInfoPlus_Fname_En { get; set; }
        public string UInfoPlus_Fname_Ar { get; set; }
        public string UInfo_Lname_En { get; set; }
        public string UInfo_Lname_Ar { get; set; }
        public string UInfo_Photo { get; set; }
        public string Id { get; set; }
        public System.DateTime UInfo_DateTime { get; set; }
        public string UInfo_Publisher { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
