//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppletSoftware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetProject
    {
        public string Project_Id { get; set; }
        public string Project_Name_Ar { get; set; }
        public string Project_Name_En { get; set; }
        public System.DateTime Project_DateTime { get; set; }
        public string Project_Photo { get; set; }
        public string Project_Url { get; set; }
        public string Project_Descrption_Ar { get; set; }
        public string Project_Descrption_En { get; set; }
        public string PCat_Id { get; set; }
        public string Id { get; set; }
    
        public virtual AspNetProjectsCategory AspNetProjectsCategory { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
