//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppletSoftware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetPlansCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetPlansCategory()
        {
            this.AspNetPlans = new HashSet<AspNetPlan>();
        }
    
        public string PlanCat_Id { get; set; }
        public string PlanCat_Name_Ar { get; set; }
        public string PlanCat_Name_En { get; set; }
        public string PlanCat_Description_Ar { get; set; }
        public string PlanCat_Description_En { get; set; }
        public System.DateTime PlanCat_DateTime { get; set; }
        public string Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetPlan> AspNetPlans { get; set; }
    }
}
