//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppletSoftware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetMessage
    {
        public string Message_Id { get; set; }
        public string Message_Email { get; set; }
        public string Message_Subject { get; set; }
        public string Message_Content { get; set; }
        public bool Message_Active { get; set; }
        public bool Message_Response { get; set; }
        public System.DateTime Message_DateTime { get; set; }
    }
}
