//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppletSoftware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetTestmonial
    {
        public string Testmonial_Id { get; set; }
        public string Testmonial_Question_Ar { get; set; }
        public string Testmonial_Question_En { get; set; }
        public string Testmonial_Answer_Ar { get; set; }
        public string Testmonial_Answer_En { get; set; }
        public System.DateTime Testmonial_DateTime { get; set; }
        public string Testmonial_ClientName_Ar { get; set; }
        public string Testmonial_ClientName_En { get; set; }
        public string Testmonial_ClientJobTitle_Ar { get; set; }
        public string Testmonial_ClientJobTitle_En { get; set; }
        public string Testmonial_ClientPhoto { get; set; }
        public string TsCat_Id { get; set; }
        public string Id { get; set; }
    
        public virtual AspNetTestmonialsCategory AspNetTestmonialsCategory { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
