//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppletSoftware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetClient
    {
        public string Client_Id { get; set; }
        public string Client_Fname_Ar { get; set; }
        public string Client_Fname_En { get; set; }
        public string Client_Lname_Ar { get; set; }
        public string Client_Lname_En { get; set; }
        public string Client_Email { get; set; }
        public string Client_PhoneNumber { get; set; }
        public string Client_CompanyName_Ar { get; set; }
        public string Client_CompanyName_En { get; set; }
        public string Client_Address_Ar { get; set; }
        public string Client_Address_En { get; set; }
        public System.DateTime Client_DateTime { get; set; }
        public string ClCat_Id { get; set; }
        public string Id { get; set; }
        public string Client_Photo { get; set; }
    
        public virtual AspNetClientsCategory AspNetClientsCategory { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
