//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppletSoftware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetNewsLetter
    {
        public string Letter_Id { get; set; }
        public string Letter_Email { get; set; }
        public bool Letter_Active { get; set; }
        public bool Letter_Response { get; set; }
        public System.DateTime Letter_DateTime { get; set; }
    }
}
