//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppletSoftware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetNotification
    {
        public string Notify_Id { get; set; }
        public string Notify_Manager_Name { get; set; }
        public string Notify_Manager_Photo { get; set; }
        public string Notify_Title { get; set; }
        public System.DateTime Notify_DateTime { get; set; }
        public bool Notify_Active { get; set; }
        public string Notify_Action { get; set; }
        public string Notify_Manager_Id { get; set; }
    }
}
