//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppletSoftware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetTeam
    {
        public string Team_Id { get; set; }
        public string Team_Fname_Ar { get; set; }
        public string Team_Fname_En { get; set; }
        public string Team_Lname_Ar { get; set; }
        public string Team_Lname_En { get; set; }
        public string Team_Email { get; set; }
        public string Team_Phone { get; set; }
        public string Team_Photo { get; set; }
        public System.DateTime Team_DateTime { get; set; }
        public string TCat_Id { get; set; }
        public string Id { get; set; }
        public decimal Team_Salary { get; set; }
        public string Team_JobTitle_Ar { get; set; }
        public string Team_JobTitle_En { get; set; }
    
        public virtual AspNetTeamsCategory AspNetTeamsCategory { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
