//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppletSoftware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetPlanOrder
    {
        public string Order_Id { get; set; }
        public string Order_Email { get; set; }
        public string Order_Phone { get; set; }
        public string Order_Plan { get; set; }
        public string Order_Message { get; set; }
        public string Order_Fname { get; set; }
        public string Order_Lname { get; set; }
        public bool Order_Response { get; set; }
        public System.DateTime Order_DateTime { get; set; }
    }
}
